version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: network_service
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  api-gateway:
    build: ../backend/api-gateway
    env_file: ../.env.example
    environment:
      - GATEWAY_PORT=3000
      - GRPC_ADDR=business-service:50051
    ports:
      - "3000:3000"
    depends_on:
      - business-service

  business-service:
    build: ../backend/business-service
    env_file: ../.env.example
    environment:
      - PORT=3001
      - GRPC_PORT=50051
    ports:
      - "3001:3001"
      - "50051:50051"
    depends_on:
      - db

  frontend:
    build: ../frontend/client-app
    env_file: ../frontend/client-app/.env.example
    ports:
      - "3002:3002"
    depends_on:
      - api-gateway

volumes:
  db-data:
